### ISSUE TITLE
Exploring the Filter Bubble: The Effect of Using Recommender Systems on Content Diversity

### ISSUE THREAD

**Issue by rishigoel** [ndey96/rec-sys#15]
http://wwwconference.org/proceedings/www2014/proceedings/p677.pdf

**Comment by ndey96** [comment]
My notes:
- filter bubble describes the potential for online personalization to isolate people from a diversity of content
- filter bubble present in collaborative filtering systems
- try to answer 2 questions:
    - Do recommender systems expose users to narrower content over time?
    - How does the experience of users who take recommendations differ from that of users who do not regularly take recommendations?
- MovieLens (movielens.org) is a non-profit movie recommendation service which publishes open datasets from real users
    - uses item-based collaborative filtering - same technique as amazon, youtube, spotify
- They use “tag-genomes” to measure diversity
    - tags map movies to a latent space which can be used to determine similarity between movies
    - they use tag diversity as their metric - average movie tag distance
- Using the time series data of movielens recommendations, they show that the average movie tag distance decreased as users continued to use the platfrom
- Surprisingly, they also showed that users liked their recommended movies less as time went on using accuracy metrics
- The more often a user interacted with a RS, the slower their recommendations narrowed
