### ISSUE TITLE
On the Role of Diversity in Conversational Recommender Systems

### ISSUE THREAD

**Issue by MatthewMcLeod** [ndey96/rec-sys#37]
From Case Based Reasoning and Research Conference.

Idea: Evaluate Diversity based on steps it takes recommendation conversational agent to get correct recommendation. 

Findings:
- Including diversity into the recommendations can reduce steps by 20%.
- Diversity is not always better. Sometimes it is better to start with diverse recommendations and as the number of steps increase, become less and less diverse.

**Comment by ndey96** [comment]
@MatthewMcLeod link up fam
