### ISSUE TITLE
Limits to Surprise in Recommender Systems

### ISSUE THREAD

**Issue by ndey96** [ndey96/rec-sys#6]
https://arxiv.org/pdf/1807.03905.pdf

Matt brought this one up

**Comment by ndey96** [comment]
My notes:
- surprising, serendipitous, and diverse are all synonyms in RS literature
- Herlocker et al. : “A serendipitous recommendation helps the user find a surprisingly interesting item he might not have otherwise discovered.”

**Comment by ColeJackes** [comment]
Yesterday I implemented/wrote about 5 of the metrics. There are still 3 more that need work.
